make the code build with lua-5.4.x
Otherwise the build would fail like this:

gcc -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  -D_GNU_SOURCE -Wall -Wno-address -fno-strict-overflow -rdynamic -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -o elinks lib.o vernum.o -lssl -lcrypto -L/usr/lib -llua -lm -Wl,--as-needed -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -ldl  -lgpm -lz -lbz2 -lidn2 -lexpat
/usr/bin/ld: lib.o: in function `l_tmpname':
/home/kdudka/fedora/elinks/elinks-0.12pre6/src/scripting/lua/core.c:252: warning: the use of `tempnam' is dangerous, better use `mkstemp'
/usr/bin/ld: lib.o: in function `script_hook_pre_format_html':
/home/kdudka/fedora/elinks/elinks-0.12pre6/src/scripting/lua/hooks.c:147: undefined reference to `lua_strlen'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:41: elinks] Error 1
make[1]: Leaving directory '/home/kdudka/fedora/elinks/elinks-0.12pre6/src'
make: *** [Makefile.lib:269: all-recursive] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.1Mc5xz (%build)